/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as HomeRouteImport } from './routes/home'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as NavigatorRouteImport } from './routes/navigator'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as StatesRouteImport } from './routes/states'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthPosterLoginRouteImport } from './routes/auth.poster-login'
import { Route as AuthRoleRouteImport } from './routes/auth.role'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as CommunitiesIndexRouteImport } from './routes/communities.index'
import { Route as CommunitiesCommunityIdRouteImport } from './routes/communities.$communityId'
import { Route as CommunitiesNewRouteImport } from './routes/communities.new'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as OpportunitiesOppIdRouteImport } from './routes/opportunities.$oppId'
import { Route as PosterIndexRouteImport } from './routes/poster.index'
import { Route as PosterAnalyticsRouteImport } from './routes/poster.analytics'
import { Route as PosterApplicationsRouteImport } from './routes/poster.applications'
import { Route as PosterCalendarRouteImport } from './routes/poster.calendar'
import { Route as PosterNewRouteImport } from './routes/poster.new'
import { Route as PosterOpportunitiesRouteImport } from './routes/poster.opportunities'
import { Route as PosterOrganizationRouteImport } from './routes/poster.organization'
import { Route as SignupIndexRouteImport } from './routes/signup.index'
import { Route as SignupPosterRouteImport } from './routes/signup.poster'
import { Route as SignupStudentRouteImport } from './routes/signup.student'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorRoute = NavigatorRouteImport.update({
  id: '/navigator',
  path: '/navigator',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesRoute = StatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPosterLoginRoute = AuthPosterLoginRouteImport.update({
  id: '/auth/poster-login',
  path: '/auth/poster-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoleRoute = AuthRoleRouteImport.update({
  id: '/auth/role',
  path: '/auth/role',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesCommunityIdRoute = CommunitiesCommunityIdRouteImport.update({
  id: '/communities/$communityId',
  path: '/communities/$communityId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesNewRoute = CommunitiesNewRouteImport.update({
  id: '/communities/new',
  path: '/communities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesOppIdRoute = OpportunitiesOppIdRouteImport.update({
  id: '/opportunities/$oppId',
  path: '/opportunities/$oppId',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterIndexRoute = PosterIndexRouteImport.update({
  id: '/poster/',
  path: '/poster/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterAnalyticsRoute = PosterAnalyticsRouteImport.update({
  id: '/poster/analytics',
  path: '/poster/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterApplicationsRoute = PosterApplicationsRouteImport.update({
  id: '/poster/applications',
  path: '/poster/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterCalendarRoute = PosterCalendarRouteImport.update({
  id: '/poster/calendar',
  path: '/poster/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterNewRoute = PosterNewRouteImport.update({
  id: '/poster/new',
  path: '/poster/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterOpportunitiesRoute = PosterOpportunitiesRouteImport.update({
  id: '/poster/opportunities',
  path: '/poster/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterOrganizationRoute = PosterOrganizationRouteImport.update({
  id: '/poster/organization',
  path: '/poster/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupPosterRoute = SignupPosterRouteImport.update({
  id: '/signup/poster',
  path: '/signup/poster',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupStudentRoute = SignupStudentRouteImport.update({
  id: '/signup/student',
  path: '/signup/student',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/calendar': typeof CalendarRoute
  '/home': typeof HomeRoute
  '/membership': typeof MembershipRoute
  '/navigator': typeof NavigatorRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/states': typeof StatesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/poster-login': typeof AuthPosterLoginRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/communities/new': typeof CommunitiesNewRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/opportunities/$oppId': typeof OpportunitiesOppIdRoute
  '/poster/analytics': typeof PosterAnalyticsRoute
  '/poster/applications': typeof PosterApplicationsRoute
  '/poster/calendar': typeof PosterCalendarRoute
  '/poster/new': typeof PosterNewRoute
  '/poster/opportunities': typeof PosterOpportunitiesRoute
  '/poster/organization': typeof PosterOrganizationRoute
  '/signup/poster': typeof SignupPosterRoute
  '/signup/student': typeof SignupStudentRoute
  '/auth/': typeof AuthIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/poster/': typeof PosterIndexRoute
  '/signup/': typeof SignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/calendar': typeof CalendarRoute
  '/home': typeof HomeRoute
  '/membership': typeof MembershipRoute
  '/navigator': typeof NavigatorRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/states': typeof StatesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/poster-login': typeof AuthPosterLoginRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/communities/new': typeof CommunitiesNewRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/opportunities/$oppId': typeof OpportunitiesOppIdRoute
  '/poster/analytics': typeof PosterAnalyticsRoute
  '/poster/applications': typeof PosterApplicationsRoute
  '/poster/calendar': typeof PosterCalendarRoute
  '/poster/new': typeof PosterNewRoute
  '/poster/opportunities': typeof PosterOpportunitiesRoute
  '/poster/organization': typeof PosterOrganizationRoute
  '/signup/poster': typeof SignupPosterRoute
  '/signup/student': typeof SignupStudentRoute
  '/auth': typeof AuthIndexRoute
  '/communities': typeof CommunitiesIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/poster': typeof PosterIndexRoute
  '/signup': typeof SignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/applications': typeof ApplicationsRoute
  '/calendar': typeof CalendarRoute
  '/home': typeof HomeRoute
  '/membership': typeof MembershipRoute
  '/navigator': typeof NavigatorRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/states': typeof StatesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/poster-login': typeof AuthPosterLoginRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/communities/new': typeof CommunitiesNewRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/opportunities/$oppId': typeof OpportunitiesOppIdRoute
  '/poster/analytics': typeof PosterAnalyticsRoute
  '/poster/applications': typeof PosterApplicationsRoute
  '/poster/calendar': typeof PosterCalendarRoute
  '/poster/new': typeof PosterNewRoute
  '/poster/opportunities': typeof PosterOpportunitiesRoute
  '/poster/organization': typeof PosterOrganizationRoute
  '/signup/poster': typeof SignupPosterRoute
  '/signup/student': typeof SignupStudentRoute
  '/auth/': typeof AuthIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/poster/': typeof PosterIndexRoute
  '/signup/': typeof SignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/calendar'
    | '/home'
    | '/membership'
    | '/navigator'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/saved'
    | '/states'
    | '/onboarding'
    | '/auth/callback'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/poster-login'
    | '/auth/role'
    | '/auth/signup'
    | '/auth/verify'
    | '/communities/$communityId'
    | '/communities/new'
    | '/legal/privacy'
    | '/legal/terms'
    | '/opportunities/$oppId'
    | '/poster/analytics'
    | '/poster/applications'
    | '/poster/calendar'
    | '/poster/new'
    | '/poster/opportunities'
    | '/poster/organization'
    | '/signup/poster'
    | '/signup/student'
    | '/auth/'
    | '/communities/'
    | '/opportunities/'
    | '/poster/'
    | '/signup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/calendar'
    | '/home'
    | '/membership'
    | '/navigator'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/saved'
    | '/states'
    | '/onboarding'
    | '/auth/callback'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/poster-login'
    | '/auth/role'
    | '/auth/signup'
    | '/auth/verify'
    | '/communities/$communityId'
    | '/communities/new'
    | '/legal/privacy'
    | '/legal/terms'
    | '/opportunities/$oppId'
    | '/poster/analytics'
    | '/poster/applications'
    | '/poster/calendar'
    | '/poster/new'
    | '/poster/opportunities'
    | '/poster/organization'
    | '/signup/poster'
    | '/signup/student'
    | '/auth'
    | '/communities'
    | '/opportunities'
    | '/poster'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/applications'
    | '/calendar'
    | '/home'
    | '/membership'
    | '/navigator'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/saved'
    | '/states'
    | '/_authenticated/onboarding'
    | '/auth/callback'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/poster-login'
    | '/auth/role'
    | '/auth/signup'
    | '/auth/verify'
    | '/communities/$communityId'
    | '/communities/new'
    | '/legal/privacy'
    | '/legal/terms'
    | '/opportunities/$oppId'
    | '/poster/analytics'
    | '/poster/applications'
    | '/poster/calendar'
    | '/poster/new'
    | '/poster/opportunities'
    | '/poster/organization'
    | '/signup/poster'
    | '/signup/student'
    | '/auth/'
    | '/communities/'
    | '/opportunities/'
    | '/poster/'
    | '/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApplicationsRoute: typeof ApplicationsRoute
  CalendarRoute: typeof CalendarRoute
  HomeRoute: typeof HomeRoute
  MembershipRoute: typeof MembershipRoute
  NavigatorRoute: typeof NavigatorRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  StatesRoute: typeof StatesRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPosterLoginRoute: typeof AuthPosterLoginRoute
  AuthRoleRoute: typeof AuthRoleRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  CommunitiesCommunityIdRoute: typeof CommunitiesCommunityIdRoute
  CommunitiesNewRoute: typeof CommunitiesNewRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  OpportunitiesOppIdRoute: typeof OpportunitiesOppIdRoute
  PosterAnalyticsRoute: typeof PosterAnalyticsRoute
  PosterApplicationsRoute: typeof PosterApplicationsRoute
  PosterCalendarRoute: typeof PosterCalendarRoute
  PosterNewRoute: typeof PosterNewRoute
  PosterOpportunitiesRoute: typeof PosterOpportunitiesRoute
  PosterOrganizationRoute: typeof PosterOrganizationRoute
  SignupPosterRoute: typeof SignupPosterRoute
  SignupStudentRoute: typeof SignupStudentRoute
  AuthIndexRoute: typeof AuthIndexRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  PosterIndexRoute: typeof PosterIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator': {
      id: '/navigator'
      path: '/navigator'
      fullPath: '/navigator'
      preLoaderRoute: typeof NavigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states': {
      id: '/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof StatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/poster-login': {
      id: '/auth/poster-login'
      path: '/auth/poster-login'
      fullPath: '/auth/poster-login'
      preLoaderRoute: typeof AuthPosterLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/role': {
      id: '/auth/role'
      path: '/auth/role'
      fullPath: '/auth/role'
      preLoaderRoute: typeof AuthRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/': {
      id: '/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$communityId': {
      id: '/communities/$communityId'
      path: '/communities/$communityId'
      fullPath: '/communities/$communityId'
      preLoaderRoute: typeof CommunitiesCommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/new': {
      id: '/communities/new'
      path: '/communities/new'
      fullPath: '/communities/new'
      preLoaderRoute: typeof CommunitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$oppId': {
      id: '/opportunities/$oppId'
      path: '/opportunities/$oppId'
      fullPath: '/opportunities/$oppId'
      preLoaderRoute: typeof OpportunitiesOppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/': {
      id: '/poster/'
      path: '/poster'
      fullPath: '/poster/'
      preLoaderRoute: typeof PosterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/analytics': {
      id: '/poster/analytics'
      path: '/poster/analytics'
      fullPath: '/poster/analytics'
      preLoaderRoute: typeof PosterAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/applications': {
      id: '/poster/applications'
      path: '/poster/applications'
      fullPath: '/poster/applications'
      preLoaderRoute: typeof PosterApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/calendar': {
      id: '/poster/calendar'
      path: '/poster/calendar'
      fullPath: '/poster/calendar'
      preLoaderRoute: typeof PosterCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/new': {
      id: '/poster/new'
      path: '/poster/new'
      fullPath: '/poster/new'
      preLoaderRoute: typeof PosterNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/opportunities': {
      id: '/poster/opportunities'
      path: '/poster/opportunities'
      fullPath: '/poster/opportunities'
      preLoaderRoute: typeof PosterOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/organization': {
      id: '/poster/organization'
      path: '/poster/organization'
      fullPath: '/poster/organization'
      preLoaderRoute: typeof PosterOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/poster': {
      id: '/signup/poster'
      path: '/signup/poster'
      fullPath: '/signup/poster'
      preLoaderRoute: typeof SignupPosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/student': {
      id: '/signup/student'
      path: '/signup/student'
      fullPath: '/signup/student'
      preLoaderRoute: typeof SignupStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApplicationsRoute: ApplicationsRoute,
  CalendarRoute: CalendarRoute,
  HomeRoute: HomeRoute,
  MembershipRoute: MembershipRoute,
  NavigatorRoute: NavigatorRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  StatesRoute: StatesRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPosterLoginRoute: AuthPosterLoginRoute,
  AuthRoleRoute: AuthRoleRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  CommunitiesCommunityIdRoute: CommunitiesCommunityIdRoute,
  CommunitiesNewRoute: CommunitiesNewRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  OpportunitiesOppIdRoute: OpportunitiesOppIdRoute,
  PosterAnalyticsRoute: PosterAnalyticsRoute,
  PosterApplicationsRoute: PosterApplicationsRoute,
  PosterCalendarRoute: PosterCalendarRoute,
  PosterNewRoute: PosterNewRoute,
  PosterOpportunitiesRoute: PosterOpportunitiesRoute,
  PosterOrganizationRoute: PosterOrganizationRoute,
  SignupPosterRoute: SignupPosterRoute,
  SignupStudentRoute: SignupStudentRoute,
  AuthIndexRoute: AuthIndexRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  PosterIndexRoute: PosterIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
