/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as HomeRouteImport } from './routes/home'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as NavigatorRouteImport } from './routes/navigator'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as StatesRouteImport } from './routes/states'
import { Route as CommunitiesIndexRouteImport } from './routes/communities.index'
import { Route as CommunitiesCommunityIdRouteImport } from './routes/communities.$communityId'
import { Route as CommunitiesNewRouteImport } from './routes/communities.new'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as OpportunitiesOppIdRouteImport } from './routes/opportunities.$oppId'
import { Route as PosterIndexRouteImport } from './routes/poster.index'
import { Route as PosterAnalyticsRouteImport } from './routes/poster.analytics'
import { Route as PosterApplicationsRouteImport } from './routes/poster.applications'
import { Route as PosterCalendarRouteImport } from './routes/poster.calendar'
import { Route as PosterNewRouteImport } from './routes/poster.new'
import { Route as PosterOpportunitiesRouteImport } from './routes/poster.opportunities'
import { Route as PosterOrganizationRouteImport } from './routes/poster.organization'
import { Route as SignupIndexRouteImport } from './routes/signup.index'
import { Route as SignupPosterRouteImport } from './routes/signup.poster'
import { Route as SignupStudentRouteImport } from './routes/signup.student'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorRoute = NavigatorRouteImport.update({
  id: '/navigator',
  path: '/navigator',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesRoute = StatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesCommunityIdRoute = CommunitiesCommunityIdRouteImport.update({
  id: '/communities/$communityId',
  path: '/communities/$communityId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesNewRoute = CommunitiesNewRouteImport.update({
  id: '/communities/new',
  path: '/communities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesOppIdRoute = OpportunitiesOppIdRouteImport.update({
  id: '/opportunities/$oppId',
  path: '/opportunities/$oppId',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterIndexRoute = PosterIndexRouteImport.update({
  id: '/poster/',
  path: '/poster/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterAnalyticsRoute = PosterAnalyticsRouteImport.update({
  id: '/poster/analytics',
  path: '/poster/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterApplicationsRoute = PosterApplicationsRouteImport.update({
  id: '/poster/applications',
  path: '/poster/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterCalendarRoute = PosterCalendarRouteImport.update({
  id: '/poster/calendar',
  path: '/poster/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterNewRoute = PosterNewRouteImport.update({
  id: '/poster/new',
  path: '/poster/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterOpportunitiesRoute = PosterOpportunitiesRouteImport.update({
  id: '/poster/opportunities',
  path: '/poster/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterOrganizationRoute = PosterOrganizationRouteImport.update({
  id: '/poster/organization',
  path: '/poster/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupPosterRoute = SignupPosterRouteImport.update({
  id: '/signup/poster',
  path: '/signup/poster',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupStudentRoute = SignupStudentRouteImport.update({
  id: '/signup/student',
  path: '/signup/student',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/calendar': typeof CalendarRoute
  '/home': typeof HomeRoute
  '/membership': typeof MembershipRoute
  '/navigator': typeof NavigatorRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/states': typeof StatesRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/communities/new': typeof CommunitiesNewRoute
  '/opportunities/$oppId': typeof OpportunitiesOppIdRoute
  '/poster/analytics': typeof PosterAnalyticsRoute
  '/poster/applications': typeof PosterApplicationsRoute
  '/poster/calendar': typeof PosterCalendarRoute
  '/poster/new': typeof PosterNewRoute
  '/poster/opportunities': typeof PosterOpportunitiesRoute
  '/poster/organization': typeof PosterOrganizationRoute
  '/signup/poster': typeof SignupPosterRoute
  '/signup/student': typeof SignupStudentRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/poster/': typeof PosterIndexRoute
  '/signup/': typeof SignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/calendar': typeof CalendarRoute
  '/home': typeof HomeRoute
  '/membership': typeof MembershipRoute
  '/navigator': typeof NavigatorRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/states': typeof StatesRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/communities/new': typeof CommunitiesNewRoute
  '/opportunities/$oppId': typeof OpportunitiesOppIdRoute
  '/poster/analytics': typeof PosterAnalyticsRoute
  '/poster/applications': typeof PosterApplicationsRoute
  '/poster/calendar': typeof PosterCalendarRoute
  '/poster/new': typeof PosterNewRoute
  '/poster/opportunities': typeof PosterOpportunitiesRoute
  '/poster/organization': typeof PosterOrganizationRoute
  '/signup/poster': typeof SignupPosterRoute
  '/signup/student': typeof SignupStudentRoute
  '/communities': typeof CommunitiesIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/poster': typeof PosterIndexRoute
  '/signup': typeof SignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/calendar': typeof CalendarRoute
  '/home': typeof HomeRoute
  '/membership': typeof MembershipRoute
  '/navigator': typeof NavigatorRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/states': typeof StatesRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/communities/new': typeof CommunitiesNewRoute
  '/opportunities/$oppId': typeof OpportunitiesOppIdRoute
  '/poster/analytics': typeof PosterAnalyticsRoute
  '/poster/applications': typeof PosterApplicationsRoute
  '/poster/calendar': typeof PosterCalendarRoute
  '/poster/new': typeof PosterNewRoute
  '/poster/opportunities': typeof PosterOpportunitiesRoute
  '/poster/organization': typeof PosterOrganizationRoute
  '/signup/poster': typeof SignupPosterRoute
  '/signup/student': typeof SignupStudentRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/poster/': typeof PosterIndexRoute
  '/signup/': typeof SignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/calendar'
    | '/home'
    | '/membership'
    | '/navigator'
    | '/notifications'
    | '/profile'
    | '/saved'
    | '/states'
    | '/communities/$communityId'
    | '/communities/new'
    | '/opportunities/$oppId'
    | '/poster/analytics'
    | '/poster/applications'
    | '/poster/calendar'
    | '/poster/new'
    | '/poster/opportunities'
    | '/poster/organization'
    | '/signup/poster'
    | '/signup/student'
    | '/communities/'
    | '/opportunities/'
    | '/poster/'
    | '/signup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/calendar'
    | '/home'
    | '/membership'
    | '/navigator'
    | '/notifications'
    | '/profile'
    | '/saved'
    | '/states'
    | '/communities/$communityId'
    | '/communities/new'
    | '/opportunities/$oppId'
    | '/poster/analytics'
    | '/poster/applications'
    | '/poster/calendar'
    | '/poster/new'
    | '/poster/opportunities'
    | '/poster/organization'
    | '/signup/poster'
    | '/signup/student'
    | '/communities'
    | '/opportunities'
    | '/poster'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/calendar'
    | '/home'
    | '/membership'
    | '/navigator'
    | '/notifications'
    | '/profile'
    | '/saved'
    | '/states'
    | '/communities/$communityId'
    | '/communities/new'
    | '/opportunities/$oppId'
    | '/poster/analytics'
    | '/poster/applications'
    | '/poster/calendar'
    | '/poster/new'
    | '/poster/opportunities'
    | '/poster/organization'
    | '/signup/poster'
    | '/signup/student'
    | '/communities/'
    | '/opportunities/'
    | '/poster/'
    | '/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  CalendarRoute: typeof CalendarRoute
  HomeRoute: typeof HomeRoute
  MembershipRoute: typeof MembershipRoute
  NavigatorRoute: typeof NavigatorRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  StatesRoute: typeof StatesRoute
  CommunitiesCommunityIdRoute: typeof CommunitiesCommunityIdRoute
  CommunitiesNewRoute: typeof CommunitiesNewRoute
  OpportunitiesOppIdRoute: typeof OpportunitiesOppIdRoute
  PosterAnalyticsRoute: typeof PosterAnalyticsRoute
  PosterApplicationsRoute: typeof PosterApplicationsRoute
  PosterCalendarRoute: typeof PosterCalendarRoute
  PosterNewRoute: typeof PosterNewRoute
  PosterOpportunitiesRoute: typeof PosterOpportunitiesRoute
  PosterOrganizationRoute: typeof PosterOrganizationRoute
  SignupPosterRoute: typeof SignupPosterRoute
  SignupStudentRoute: typeof SignupStudentRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  PosterIndexRoute: typeof PosterIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator': {
      id: '/navigator'
      path: '/navigator'
      fullPath: '/navigator'
      preLoaderRoute: typeof NavigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states': {
      id: '/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof StatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/': {
      id: '/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$communityId': {
      id: '/communities/$communityId'
      path: '/communities/$communityId'
      fullPath: '/communities/$communityId'
      preLoaderRoute: typeof CommunitiesCommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/new': {
      id: '/communities/new'
      path: '/communities/new'
      fullPath: '/communities/new'
      preLoaderRoute: typeof CommunitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$oppId': {
      id: '/opportunities/$oppId'
      path: '/opportunities/$oppId'
      fullPath: '/opportunities/$oppId'
      preLoaderRoute: typeof OpportunitiesOppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/': {
      id: '/poster/'
      path: '/poster'
      fullPath: '/poster/'
      preLoaderRoute: typeof PosterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/analytics': {
      id: '/poster/analytics'
      path: '/poster/analytics'
      fullPath: '/poster/analytics'
      preLoaderRoute: typeof PosterAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/applications': {
      id: '/poster/applications'
      path: '/poster/applications'
      fullPath: '/poster/applications'
      preLoaderRoute: typeof PosterApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/calendar': {
      id: '/poster/calendar'
      path: '/poster/calendar'
      fullPath: '/poster/calendar'
      preLoaderRoute: typeof PosterCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/new': {
      id: '/poster/new'
      path: '/poster/new'
      fullPath: '/poster/new'
      preLoaderRoute: typeof PosterNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/opportunities': {
      id: '/poster/opportunities'
      path: '/poster/opportunities'
      fullPath: '/poster/opportunities'
      preLoaderRoute: typeof PosterOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/organization': {
      id: '/poster/organization'
      path: '/poster/organization'
      fullPath: '/poster/organization'
      preLoaderRoute: typeof PosterOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/poster': {
      id: '/signup/poster'
      path: '/signup/poster'
      fullPath: '/signup/poster'
      preLoaderRoute: typeof SignupPosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/student': {
      id: '/signup/student'
      path: '/signup/student'
      fullPath: '/signup/student'
      preLoaderRoute: typeof SignupStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  CalendarRoute: CalendarRoute,
  HomeRoute: HomeRoute,
  MembershipRoute: MembershipRoute,
  NavigatorRoute: NavigatorRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  StatesRoute: StatesRoute,
  CommunitiesCommunityIdRoute: CommunitiesCommunityIdRoute,
  CommunitiesNewRoute: CommunitiesNewRoute,
  OpportunitiesOppIdRoute: OpportunitiesOppIdRoute,
  PosterAnalyticsRoute: PosterAnalyticsRoute,
  PosterApplicationsRoute: PosterApplicationsRoute,
  PosterCalendarRoute: PosterCalendarRoute,
  PosterNewRoute: PosterNewRoute,
  PosterOpportunitiesRoute: PosterOpportunitiesRoute,
  PosterOrganizationRoute: PosterOrganizationRoute,
  SignupPosterRoute: SignupPosterRoute,
  SignupStudentRoute: SignupStudentRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  PosterIndexRoute: PosterIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
